<?php
namespace Vaimo\ComposerPatches\Patch;

class Report
{
    public function generate($patches, $directory)
    {
        $outputLines = array();

        $outputLines[] = 'This file was automatically generated by Composer Patches';
        $outputLines[] = 'Patches applied to this directory:';
        $outputLines[] = '';

        foreach ($patches as $source => $description) {
            $outputLines[] = $description;
            $outputLines[] = 'Source: ' . $source;
            $outputLines[] = '';
            $outputLines[] = '';
        }

        file_put_contents($directory . '/PATCHES.txt', implode("\n", $outputLines));
    }
}
