<?php
namespace Vaimo\ComposerPatches;

class Environment
{
    const FORCE_REAPPLY = 'COMPOSER_FORCE_PATCH_REAPPLY';
    const EXIT_ON_FAIL = 'COMPOSER_EXIT_ON_PATCH_FAILURE';
    const PACKAGE_SKIP = 'COMPOSER_SKIP_PATCH_PACKAGES';
    const PREFER_OWNER = 'COMPOSER_PATCHES_PREFER_OWNER';
}
